name = "rethen-ai"
pages_build_output_dir = "out"
compatibility_date = "2026-09-13"

[[d1_databases]]
binding = "DB"
database_name = "rethen-form"
database_id = "a095c72a-aa49-4fda-a6a7-f5ae6391fa65"
